export const ERROR_CODE = {
  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  CONFLICT: "CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
